export const APPEND_PLAYLISTS = 'APPEND_PLAYLISTS'
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS'

export const FETCH_TRACKS = 'FETCH_TRACKS'

export const RETRIEVE_TRACKS_OVERVIEW = 'RETRIEVE_TRACKS_OVERVIEW'
